### ISSUE TITLE
It cannot work in scrollerView.

### ISSUE THREAD

**Issue by SpannerBear** [CoDevBlocks/Knob#1]
This is a powerful knob library！
It can not work in scrollerView very well, they have a sliding conflict.
It seems that should not change the progress at  MotionEvent.ACTION_DOWN, but MotionEvent.ACTION_MOVE, because this is too sensitive.

And unfortunately it does not have a demo project that can run.

**Comment by cosmin-cdb** [comment]
Thanks for raising this issue. I've added a fix (see ece21fb0bfead3e1382834fa86db29f840de3592). From my tests, it works fine in `ScrollView`. Let me know if a new artifact version in maven would help you and I'll make a new release.

I'll add a demo project in the near future.
